### ISSUE TITLE
Can't run the test example

### ISSUE THREAD

**Issue by erikscarlatescu** [rishavb123/ExperimentLab#10]
Hey! I tried installing your package, but I got the following error when I tried running the test example:

<img width="1192" alt="Screenshot 2024-03-13 at 4 52 41 PM" src="https://github.com/rishavb123/ExperimentLab/assets/20156870/dac1317f-66b9-47a5-8223-a077fab16e41">

Is this because I installed something incorrectly? Or is the example not working?

Thanks!

**Comment by rishavb123** [comment]
There was a minor bug in the example experiment. See this [pr](https://github.com/rishavb123/ExperimentLab/pull/11).

**Comment by rishavb123** [comment]
There was a minor bug in the example experiment. See this https://github.com/rishavb123/ExperimentLab/pull/11.
